reddit/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "subs#index"
	resources :users, only: %i(new create show)
	resource :session, only: %i(new create destroy)
	resources :subs, except: %i(destroy)
	resources :posts, except: %i(index destroy) do
		resources :comments, only: %i(new)
		member do 
			post :upvote 
			post :downvote 
		end
	end
	resources :comments, only: %i(create show) do 
		member do 
			post :upvote 
			post :downvote
		end
	end
end

reddit/app/models/comment.rb
class Comment < ApplicationRecord
	include Votable
	
	validates :body, presence: true 

	after_initialize :ensure_post_id! 
	
	belongs_to :author, 
		foreign_key: :user_id, 
		class_name: :User, 
		inverse_of: :comments 

	belongs_to :post, 
		inverse_of: :comments

	has_many :child_comments, 
		primary_key: :id,
		foreign_key: :parent_comment_id,
		class_name: :Comment

	belongs_to :parent_comment, 
		primary_key: :id, 
		foreign_key: :parent_comment_id,
		class_name: :Comment,
		optional: true 

	private 

	def ensure_post_id! 
		self.post_id ||= self.parent_comment.post_id if parent_comment
	end
end

reddit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :require_logged_in!

	def new 
		@comment = Comment.new(post_id: params[:post_id])
		render :new 
	end

	def create 
		@comment = current_user.comments.new(comment_params)
		if @comment.save 
			redirect_to post_url(@comment.post_id)
		else
			flash[:errors] = @comment.errors.full_messages
			redirect_to new_post_comment_url(@comment.post_id)
		end
	end

	def show 
		@comment = Comment.find(params[:id])
		@new_comment = @comment.child_comments.new 
		render :show
	end

	def downvote 
		vote(-1)
	end

	def upvote 
		vote(1)
	end

	private 

	def comment_params 
		params.require(:comment).permit(:body, :post_id, :parent_comment_id)
	end

	def vote(direction)
		@comment = Comment.find(params[:id])
		@user_vote = @comment.user_votes.find_or_initialize_by(user: current_user)

		unless @user_vote.update(value: direction)
			flash[:erros] = @user_vote.errors.full_messages
		end
		redirect_to comment_url(@comment)
	end

end

reddit/app/views/comments/_comment.html.erb
<p>
  <a href="<%= comment_url(comment.id) %>"><%= comment.body %></a>
</p>

<ul>
  <% comments_by_parent[comment.id].each do |child_comment| %>
    <li><%= render("comments/comment",
            comment: child_comment,
            comments_by_parent: comments_by_parent) %></li>
  <% end %>
</ul>

reddit/app/views/comments/_form.html.erb
<form action="<%= comments_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input
    type="hidden"
    name="comment[post_id]"
    value="<%= comment.post_id %>">
  <input
    type="hidden"
    name="comment[parent_comment_id]"
    value="<%= comment.parent_comment_id %>">

  <label>
    Body
    <br>
    <textarea name="comment[body]"><%= comment.body %></textarea>
  </label>
  <br>

  <input type="submit">
</form>

reddit/app/views/comments/new.html.erb
<div class="border">
  <h1>New Comment!</h1>

  <%= render "form", comment: @comment %>
</div>

reddit/app/views/comments/show.html.erb
<div class="border">
	<div>
  	<%= @comment.body %> by <%= @comment.author.username %>
		<%= @comment.votes %> upvotes
	</div>

	<form action="<%= upvote_comment_url(@comment) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Upvote">
  </form>
  <form action="<%= downvote_comment_url(@comment) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Downvote">
  </form>

  <b>Reply to this comment:</b>
  <%= render "form", comment: @new_comment %>
</div>