reddit/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "subs#index"
	resources :users, only: %i(new create show)
	resource :session, only: %i(new create destroy)
	resources :subs, except: %i(destroy)
	resources :posts, except: %i(index destroy) do
		resources :comments, only: %i(new)
		member do 
			post :upvote 
			post :downvote 
		end
	end
	resources :comments, only: %i(create show) do 
		member do 
			post :upvote 
			post :downvote
		end
	end
end

reddit/app/models/sub.rb
class Sub < ApplicationRecord
	validates :name, presence: true, uniqueness: true 

	belongs_to :moderator, 
		primary_key: :id, 
		foreign_key: :moderator_id, 
		class_name: :User, 
		inverse_of: :subs

	has_many :post_subs, inverse_of: :sub
	has_many :posts, through: :post_subs, source: :post
end

reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
	before_action :require_logged_in! 
	before_action :require_user_owns_sub!, only: %i(edit update)

	def new 
		@sub = Sub.new 
		render :new 
	end

	def create 
		@sub = current_user.subs.new(sub_params)
		if @sub.save 
			redirect_to sub_url(@sub)
		else 
			flash.now[:errors] = @sub.errors.full_messages
			render :new, status: :unprocessable_entity
		end
	end

	def index 
		@subs = Sub.all 
		render :index
	end

	def edit 
		@sub = Sub.find(params[:id])
		render :edit
	end

	def update
		@sub = Sub.find(params[:id])
		if @sub.update(sub_params)
			redirect_to sub_url(@sub)
		else
			flash.now[:errors] = @sub.errors.full_messages
			render :edit, status: :unprocessable_entity
		end
	end

	def show 
		@sub = Sub.find(params[:id])
		render :show 
	end

	private 

	def sub_params
		params.require(:sub).permit(:name, :description)
	end

	def require_user_owns_sub!
		return if current_user.subs.find_by(id: params[:id]) 
		render json: 'Forbidden', status: :forbidden 
	end
end

reddit/app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= http_method %>">

  <label>
    Name
    <input name="sub[name]" value="<%= sub.name %>">
  </label>
  <br>

  <label>
    Description
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>

  <input type="submit" value="Submit!">
</form>

reddit/app/views/subs/edit.html.erb
<div>
  <h1>Edit your Sub</h1>

  <%= render "form", sub: @sub %>
</div>

reddit/app/views/subs/index.html.erb
<div>
  <h1>All the Subs!</h1>

  <ul>
    <% @subs.each do |sub| %>
      <li><a href="<%= sub_url(sub) %>"><%= sub.name %></a><br></li>
    <% end %>
  </ul>
</div>

reddit/app/views/subs/new.html.erb
<div>
  <h1>Create a new sub!</h1>
  <%= render "form", sub: @sub %>
</div>

reddit/app/views/subs/show.html.erb
<div class="border">
  <h1>
    <%= @sub.name %>
  </h1>


  <b>Description</b>
  <p><%= @sub.description %></p>

  <a href="<%= new_post_url %>">Make New Post!</a>

  <ul>
    <% @sub.posts.each do |post| %>
      <li><a href="<%= post_url(post) %>"><%= post.title %></a></li>
    <% end %>
  </ul>
  <a href="<%= edit_sub_url(@sub) if @sub.moderator == current_user %>">Edit</a>
</div>