reddit/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "subs#index"
	resources :users, only: %i(new create show)
	resource :session, only: %i(new create destroy)
	resources :subs, except: %i(destroy)
	resources :posts, except: %i(index destroy) do
		resources :comments, only: %i(new)
		member do 
			post :upvote 
			post :downvote 
		end
	end
	resources :comments, only: %i(create show) do 
		member do 
			post :upvote 
			post :downvote
		end
	end
end

reddit/app/models/post.rb
class Post < ApplicationRecord
	include Votable 
	
	validates :title, presence: true 
	validates :subs, presence: { message: 'must have at least one sub' }

	belongs_to :author, 
		foreign_key: :user_id, 
		class_name: :User, 
		inverse_of: :posts

	has_many :post_subs, inverse_of: :post
	has_many :subs, through: :post_subs, source: :sub
	has_many :comments, inverse_of: :post

	def comments_by_parent 
		comments_by_parent = Hash.new { |h, k| h[k] = [] } 
		self.comments.includes(:author).each do |comment|
			comments_by_parent[comment.parent_comment_id] << comment
		end
		comments_by_parent
	end
end

reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :require_logged_in! 
	before_action :require_user_owns_post!, only: %i(edit update)

	def new 
		@post = Post.new 
		render :new 
	end

	def create 
		@post = current_user.posts.new(post_params)
		if @post.save 
			redirect_to post_url(@post)
		else
			flash.now[:errors] = @post.errors.full_messages
			render :new 
		end
	end

	def edit 
		@post = Post.find(params[:id])
		render :edit 
	end

	def update 
		@post = Post.find(params[:id])
		if @post.update(post_params) 
			redirect_to post_url(@post)
		else
			flash.now[:errors] = @post.errors.full_messages
			render :edit
		end
	end

	def show 
		@post = Post.find(params[:id])
		render :show 
	end

	def destroy 
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to subs_url
	end

	def downvote
    vote(-1)
  end

  def upvote
    vote(1)
  end

	private 

	def post_params
		params.require(:post).permit(:title, :content, :url, sub_ids: [])
	end

	def require_user_owns_post!
		return if current_user.posts.find_by(id: params[:id])
		render json: 'Forbidden', status: :forbidden
	end

	def vote(direction)
		@post = Post.find(params[:id])
		@user_vote = @post.user_votes.find_or_initialize_by(user: current_user)
		
		unless @user_vote.update(value: direction)
			flash[:errors] = @user_vote.errors.full_messages
		end

		redirect_to post_url(@post)
	end
end

reddit/app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>
    URL:
    <input name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>
    Content:
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if post.sub_ids.include?(sub.id) %>>
      <%= sub.name %>
    </label>
    <br>
  <% end %>

  <input type="Submit" value="Submit">
</form>

reddit/app/views/posts/edit.html.erb
<div class="border">
  <h1>Edit Post!</h1>
	<%= render "shared/errors" %>
  <%= render "form", post: @post %>
</div>

reddit/app/views/posts/new.html.erb
<div class="border">
  <h1>New Post!</h1>
	<%= render "shared/errors" %>
  <%= render "form", post: @post %>
</div>

reddit/app/views/posts/show.html.erb
<div class="border">
  <h1>
		(<%= @post.votes %>)
    <a href="<%= post_url(@post) %>"><%= @post.title %></a> by
    <%= @post.author.username %>
  </h1>

  <div>
    <b>Content:</b>

    <pre><%= @post.content %></pre>
    <br><br>
  </div>

	<form action="<%= upvote_post_url(@post) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Upvote">
  </form>
  <form action="<%= downvote_post_url(@post) %>" method="post">
    <input
      type="hidden"
      name="authenticity_token"
      value="<%= form_authenticity_token %>">
    <input type="submit" value="Downvote">
  </form>

  <br>
  <b>Subs</b>
  <ul>
    <% @post.subs.each do |sub| %>
      <li><a href="<%= sub_url(sub) %>"><%= sub.name %></a></li>
    <% end %>
  </ul>

	<h2>Comments</h2>

  <a href="<%= new_post_comment_url(@post.id) %>">Comment on this post!</a>
  <br><br>

  <ul>
    <% comments_by_parent = @post.comments_by_parent %>
    <% comments_by_parent[nil].each do |top_level_comment| %>
      <li>
        <%= render("comments/comment",
                   comment: top_level_comment,
                   comments_by_parent: comments_by_parent) %>
      </li>
    <% end %>
  </ul>

  <a href="<%= edit_post_url(@post) if @post.author == current_user %>">Edit</a>
</div>